'use client'
export const dynamic = 'force-dynamic'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import { useRouter, useParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Download, FileText, Lightbulb, BookOpen } from 'lucide-react'
import jsPDF from 'jspdf'


export default function SummaryPage() {
  const { id } = useParams()
  const router = useRouter()
  const [summary, setSummary] = useState(null)
  const [loading, setLoading] = useState(true)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    supabase.auth.getUser().then(({ data }) => {
      if (!data.user) { router.push('/login'); return }
      fetchSummary(data.user.id)
    })
  }, [id])

  async function fetchSummary(userId) {
    const { data, error } = await supabase
      .from('summaries')
      .select('*')
      .eq('id', id)
      .eq('user_id', userId)
      .single()
    if (error || !data) { router.push('/dashboard'); return }
    setSummary(data)
    setLoading(false)
  }

  async function handleDownload() {
    if (!summary) return
    setDownloading(true)

    const doc = new jsPDF({ unit: 'mm', format: 'a4' })
    const pageW = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxW = pageW - margin * 2
    let y = 20

    // Header
    doc.setFillColor(124, 106, 247)
    doc.rect(0, 0, pageW, 14, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'bold')
    doc.text('PAGELESS — PDF SUMMARISER', margin, 9)

    y = 28
    // File name
    doc.setTextColor(40, 40, 60)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    const titleLines = doc.splitTextToSize(summary.file_name.replace('.pdf', ''), maxW)
    doc.text(titleLines, margin, y)
    y += titleLines.length * 8 + 4

    // Date
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(150, 150, 170)
    doc.text(`Summarised on ${new Date(summary.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`, margin, y)
    y += 12

    // Divider
    doc.setDrawColor(200, 200, 220)
    doc.line(margin, y, pageW - margin, y)
    y += 10

    // Key Topics
    if (summary.key_topics && summary.key_topics.length > 0) {
      doc.setFontSize(13)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(124, 106, 247)
      doc.text('KEY TOPICS', margin, y)
      y += 8

      summary.key_topics.forEach((topic, i) => {
        if (y > 270) { doc.addPage(); y = 20 }
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(60, 60, 80)
        const lines = doc.splitTextToSize(`${i + 1}. ${topic.point}`, maxW - 4)
        doc.text(lines, margin + 2, y)
        y += lines.length * 6 + 4
      })
      y += 6
    }

    // Divider
    doc.setDrawColor(200, 200, 220)
    doc.line(margin, y, pageW - margin, y)
    y += 10

    // Full Summary
    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(124, 106, 247)
    doc.text('FULL SUMMARY', margin, y)
    y += 8

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(50, 50, 70)
    const paragraphs = summary.summary.split('\n\n')
    for (const para of paragraphs) {
      if (y > 270) { doc.addPage(); y = 20 }
      const lines = doc.splitTextToSize(para, maxW)
      doc.text(lines, margin, y)
      y += lines.length * 6 + 5
    }

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(180, 180, 200)
    doc.text('Generated by PageLess · pageless.app', margin, 290)

    doc.save(`${summary.file_name.replace('.pdf', '')}-summary.pdf`)
    setDownloading(false)
  }

  if (loading) {
    return (
      <main style={{ minHeight: '100vh', background: 'var(--bg)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <div className="loading-ring" />
      </main>
    )
  }

  const topics = summary.key_topics || []
  const paragraphs = summary.summary.split('\n\n').filter(p => p.trim())

  return (
    <main style={{ minHeight: '100vh', background: 'var(--bg)' }}>
      {/* Navbar */}
      <nav style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        padding: '1.25rem 2.5rem', borderBottom: '1px solid var(--border)',
        position: 'sticky', top: 0, zIndex: 50,
        background: 'rgba(10,10,15,0.9)', backdropFilter: 'blur(12px)'
      }}>
        <Link href="/dashboard" style={{ textDecoration: 'none' }}>
          <button className="btn-outline" style={{ padding: '0.5rem 1rem', fontSize: '0.85rem' }}>
            <ArrowLeft size={14} /> Dashboard
          </button>
        </Link>
        <span style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: '1.2rem', color: 'var(--accent)' }}>PageLess</span>
        <button className="btn-primary" onClick={handleDownload} disabled={downloading} style={{ padding: '0.5rem 1.25rem', fontSize: '0.85rem' }}>
          <Download size={14} /> {downloading ? 'Preparing...' : 'Download PDF'}
        </button>
      </nav>

      <div style={{ maxWidth: 780, margin: '0 auto', padding: '3rem 2rem' }}>
        {/* Title */}
        <div className="fade-up" style={{ marginBottom: '2.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '0.75rem' }}>
            <div style={{
              width: 44, height: 44, borderRadius: 12, background: 'rgba(124,106,247,0.15)',
              display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--accent)'
            }}>
              <FileText size={20} />
            </div>
            <div>
              <h1 style={{ fontFamily: 'Syne', fontWeight: 800, fontSize: '1.4rem', lineHeight: 1.2 }}>
                {summary.file_name.replace('.pdf', '')}
              </h1>
              <p style={{ color: 'var(--muted)', fontSize: '0.8rem', marginTop: '0.2rem' }}>
                {new Date(summary.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}
              </p>
            </div>
          </div>
        </div>

        {/* Key Topics */}
        {topics.length > 0 && (
          <div className="fade-up" style={{ marginBottom: '2.5rem' }}>
            <h2 style={{
              fontFamily: 'Syne', fontWeight: 700, fontSize: '1rem',
              display: 'flex', alignItems: 'center', gap: '0.5rem',
              color: 'var(--accent)', marginBottom: '1rem', textTransform: 'uppercase', letterSpacing: '0.05em'
            }}>
              <Lightbulb size={16} /> Key Topics
            </h2>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {topics.map((topic, i) => (
                <div key={i} style={{
                  background: 'var(--surface)', border: '1px solid var(--border)',
                  borderLeft: '3px solid var(--accent)', borderRadius: '0 12px 12px 0',
                  padding: '1rem 1.25rem', display: 'flex', gap: '1rem', alignItems: 'flex-start'
                }}>
                  <span style={{
                    background: 'var(--accent)', color: 'white', fontFamily: 'Syne',
                    fontWeight: 700, fontSize: '0.75rem', borderRadius: 6, padding: '0.2rem 0.5rem',
                    flexShrink: 0, marginTop: '0.1rem'
                  }}>
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <p style={{ color: 'var(--text)', lineHeight: 1.6, fontSize: '0.92rem' }}>{topic.point}</p>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Full Summary */}
        <div className="fade-up">
          <h2 style={{
            fontFamily: 'Syne', fontWeight: 700, fontSize: '1rem',
            display: 'flex', alignItems: 'center', gap: '0.5rem',
            color: 'var(--accent)', marginBottom: '1rem', textTransform: 'uppercase', letterSpacing: '0.05em'
          }}>
            <BookOpen size={16} /> Full Summary
          </h2>
          <div style={{
            background: 'var(--surface)', border: '1px solid var(--border)',
            borderRadius: 16, padding: '2rem'
          }}>
            {paragraphs.map((para, i) => (
              <p key={i} style={{
                color: 'var(--text)', lineHeight: 1.8, fontSize: '0.95rem',
                marginBottom: i < paragraphs.length - 1 ? '1.25rem' : 0
              }}>
                {para}
              </p>
            ))}
          </div>
        </div>
      </div>
    </main>
  )
}